name: Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: |
        echo "build"


  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: test
      run: |
        echo "test"
