name: Changes to pr to main
permissions: write-all

on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  check-labels:
    uses: ./.github/workflows/check-for-lable.yaml
