name: Automatic release on tag creation
permissions: write-all

on:
  workflow_call:
    inputs:
      dotNet-version:
        required: false
        type: string
        default: "8"
#  create:
#    ref_type: tag
#    tags:
#      - 'v*.*.*'
#  push:
#    tags:
#      - 'v*.*.*'
#  workflow_run:
#      workflows: ['Create tag on PR Merge']
#      types: [completed]
#  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #Fetch all history and tags

       # Get the latest tag from the repository
      - name: Get latest tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")  # Get latest tag or default to v0.0.0
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Current latest tag is $LATEST_TAG"

      - name: echo dotnet version
        run: |
          echo "dotnet version ${{ inputs.dotNet-version }}"
      
      # Upload the release artifacts and create the release
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.LATEST_TAG }}
          name: Release ${{ env.LATEST_TAG }}  # Set release name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
